### ISSUE TITLE
[BUG]: Lublog ingress port doesnt match service port

### ISSUE THREAD

**Issue by rgulden** [anza-labs/charts#21]
### What happened?

Hey boss, thanks for creating the lubelog chart. Just wanted to let you know when you use the ingress part of the chart, it creates it with port `80` but it should be port `8080` for the backend. In the templates i see `$svcPort`, not sure where thats coming from but it doesnt equal what the service is using to be created. thanks!

https://github.com/anza-labs/charts/blob/665f6c7cbed26e27137d6477b7a9d5c2934426d8/anza-labs/lubelogger/templates/ingress.yaml#L54-L55

and 

https://github.com/anza-labs/charts/blob/665f6c7cbed26e27137d6477b7a9d5c2934426d8/anza-labs/lubelogger/templates/service.yaml#L10-L14

**Comment by shanduur** [comment]
@rgulden thanks! Sorry that it took so long, but this should be fixed now in [v0.4.6](https://github.com/anza-labs/charts/releases/tag/lubelogger-0.4.6).

**Comment by rgulden** [comment]
@shanduur no worries! glad its fixed.
